### ISSUE TITLE
I tried your code but it seems always return  the camera is not yet ready.

### ISSUE THREAD

**Issue by keacifer** [JannikLassahn/hololens-photocapture#1]
I tried your code but it seems always returned"  the camera is not yet ready".

**Comment by JannikLassahn** [comment]
I'm not sure why you're experiencing this issue. Could you provide some information about your setup/environment?

**Comment by annabelfan** [comment]
Running the project on Unity for me always showed that the camera is not yet ready (even on the Holographic Emulator), it also threw a "Failed to initialize IMediaCapture" error. After building to VS and deploying remotely to my HoloLens from there it worked great though! Thanks for sharing your project @JannikLassahn
