### ISSUE TITLE
Showing "Camera failed to start" when try to export this scene to other project

### ISSUE THREAD

**Issue by VenuVc** [JannikLassahn/hololens-photocapture#2]
Hi,
Thanks for sharing this code, It is very useful.
I build it separately and works fine on my HoloLens.
But, when I try to use PhotoManager in another project which is using MRTK it shows me the text of "Camera failed to start" on my Hololesnse.
Any suggestions?

**Comment by JannikLassahn** [comment]
I'm glad you find it useful :)
Please make sure that the [WebCam capability](https://docs.unity3d.com/Manual/class-PlayerSettingsWSA.html#Capabilities) is checked. Also, there are apparently some versions of Unity where the PhotoCapture API [does not work as indented](https://issuetracker.unity3d.com/issues/windowsmr-failure-to-take-photo-capture-in-hololens).
I hope this helps in resolving your issue.

**Comment by VenuVc** [comment]
This issue is not with the Unity version as I have also tried the whole project separately and it had worked fine.
Yes, I have also enabled all required capabilities in my manifest.
But somehow I have solved this issue by deleting all other assembly files and folder except Asset and project settings from my project and now it's working fine.
Thanks, @JannikLassahn  for your help.
